archives:
- format_overrides:
  - formats:
    - zip
    goos: windows
  formats:
  - tar.gz
  name_template: '{{ .ProjectName }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm
    }}v{{ .Arm }}{{ end }}'
builds:
- binary: cluster-lifecycle
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  id: cluster-lifecycle
  ldflags:
  - -s -w -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.version={{.Version}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.commit={{.Commit}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.date={{.Date}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.builtBy=goreleaser
  main: ./cmd/cluster-lifecycle
- binary: dualstream-release-builder
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  id: dualstream-release-builder
  ldflags:
  - -s -w -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.version={{.Version}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.commit={{.Commit}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.date={{.Date}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.builtBy=goreleaser
  main: ./cmd/dualstream-release-builder
- binary: pull-from-imagestream
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  id: pull-from-imagestream
  ldflags:
  - -s -w -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.version={{.Version}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.commit={{.Commit}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.date={{.Date}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.builtBy=goreleaser
  main: ./cmd/pull-from-imagestream
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
  sort: asc
checksum:
  name_template: checksums.txt
dockers_v2:
- dockerfile: Dockerfile.goreleaser
  ids:
  - cluster-lifecycle
  - dualstream-release-builder
  - pull-from-imagestream
  images:
  - quay.io/zzlotnik/{{ .ProjectName }}
  labels:
    org.opencontainers.image.created: '{{ .Date }}'
    org.opencontainers.image.description: '{{ .ProjectName }}'
    org.opencontainers.image.revision: '{{ .FullCommit }}'
    org.opencontainers.image.source: https://github.com/cheesesashimi/{{ .ProjectName
      }}
    org.opencontainers.image.title: '{{ .ProjectName }}'
    org.opencontainers.image.url: https://github.com/cheesesashimi/{{ .ProjectName
      }}
    org.opencontainers.image.version: '{{ .Version }}'
    '{{ if index .Env "GITHUB_ACTIONS" }}com.github.actions{{else}}label-no-actions-env-1{{end}}': ''
    '{{ if index .Env "GITHUB_RUN_ID" }}com.github.actions.runId{{else}}label-no-actions-env-2{{end}}': '{{
      if index .Env "GITHUB_RUN_ID" }}{{ .Env.GITHUB_RUN_ID }}{{else}}{{end}}'
    '{{ if index .Env "GITHUB_RUN_NUMBER" }}com.github.actions.runNumber{{else}}label-no-actions-env-3{{end}}': '{{
      if index .Env "GITHUB_RUN_NUMBER" }}{{ .Env.GITHUB_RUN_NUMBER }}{{else}}{{end}}'
    '{{ if index .Env "GITHUB_WORKFLOW" }}com.github.actions.workflow{{else}}label-no-actions-env-4{{end}}': '{{
      if index .Env "GITHUB_WORKFLOW" }}{{ .Env.GITHUB_WORKFLOW }}{{else}}{{end}}'
    '{{ if index .Env "RUNNER_NAME" }}com.github.actions.runnerName{{else}}label-no-actions-env-5{{end}}': '{{
      if index .Env "RUNNER_NAME" }}{{ .Env.RUNNER_NAME }}{{else}}{{end}}'
  platforms:
  - linux/amd64
  - linux/arm64
  tags:
  - '{{ .Version }}'
  - latest
snapshot:
  version_template: '{{ incpatch .Version }}-next'
version: 2
